version: "0.5"

processes:
  backend:
    command: cd backend && python run.py
    working_dir: .
    availability:
      restart: always
    readiness_probe:
      http_get:
        host: 127.0.0.1
        port: 8000
        path: /api/health
      initial_delay_seconds: 3
      period_seconds: 5

  frontend:
    command: npx next dev --port 5000
    working_dir: .
    availability:
      restart: always
    depends_on:
      backend:
        condition: process_healthy
